import type { Metadata } from "next";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ScrollToTopButton } from "@/utils/Util";
import Popup from "@/components/Popup";

export const metadata: Metadata = {
  title: "Radio Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* <head>
        
      </head> */}
      <Header />
      {children}
      <Footer />
      <Popup/>
      <ScrollToTopButton />
    </div>
  );
}
