import type { Metadata } from "next";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ScrollToTopButton } from "@/utils/Util";
import Popup from "@/components/Popup";
import { RadioProvider } from "@/context/RadioContext";
import { LiveProvider } from "@/context/LiveContext";

export const metadata: Metadata = {
  title: "Radio Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <LiveProvider>

        <RadioProvider>
          {/* <head>
        
        </head> */}
          <Header />
          {children}
          <Footer />
          <Popup />
          <ScrollToTopButton />
        </RadioProvider>
      </LiveProvider>
    </div>
  );
}
