import type { Metadata } from "next";
import "./globals.css";
import { FormProvider } from "@/context/Context";
import { Toaster } from "sonner";
import { ScrollToTopButton } from "@/utils/Util";

export const metadata: Metadata = {
  title: "FM LAND - Online Radio HTML Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" className="rounded-full " />
        {/* <link rel="stylesheet" href="/static/css/main.e2d17f3a.css" /> */}
        {/* <link rel="stylesheet" href="/css/bootstrap.min.css" /> */}
        <link rel="stylesheet" href="/css/all.min.css" />
        {/* <link rel="stylesheet" href="/css/remixicon.css" />*/}
        <link rel="stylesheet" href="/css/style.css" /> 
      </head>
      <body className={` font-Lato `}>
        <FormProvider>
          {children}
          <Toaster
            position="top-right"
            expand={true}
            // richColors
            theme="light" 
          />
          <ScrollToTopButton />
        </FormProvider>
      </body>
    </html>
  );
}
